services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contract_system
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql

  php:
    build: backend/
    ports: ["8000:8000"]
    depends_on: [mysql]
    command: sh -lc "php -S 0.0.0.0:8000 -t public"

  adminer:
    image: adminer
    ports: ["8080:8080"]
    environment: { ADMINER_DEFAULT_SERVER: mysql }
    depends_on: [mysql]

volumes: { dbdata: {} }