services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mojeMilaJulinka
      MYSQL_DATABASE: contract_system
      MYSQL_USER: contractor
      MYSQL_PASSWORD: mojeMilaJulinka
    volumes:
      - dbdata:/var/lib/mysql

  app:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    depends_on: [mysql]
    ports: ["1403:80"]
    environment:
      APP_ENV: prod
      APP_SECRET: change-me
      DATABASE_URL: "mysql://contractor:mojeMilaJulinka@mysql:3306/contract_system?serverVersion=8.0.31&charset=utf8mb4"
      JWT_PASSPHRASE: "heslo123"
    volumes:
      - jwtkeys:/var/www/html/config/jwt  # perzistence klíčů, ale žádný kódový mount!

volumes:
  dbdata:
  jwtkeys:
