security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity: { class: App\Entity\User, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/
      stateless: true
      provider: app_user_provider
      jwt: ~    # Lexik JWT authenticator

  access_control:
    - { path: ^/login$, roles: PUBLIC_ACCESS }   # login je veřejný
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }     # vše ostatní vyžaduje token
